### PR TITLE
Fix the release workflow

### PR DESCRIPTION
**Pull request by jmatsu**
git-pr-release couldn't work as expected on github actions. I've created a bash script that does the same thing to git-pr-release but support tags.

For the release PR style, please check https://github.com/DeployGate/upload-app-bitrise-step/pull/25

### CODE REVIEW

**Comment by enomoto-kazuya** [comment]
https://github.com/DeployGate/upload-app-bitrise-step/pull/25 こちらのPRにはある以下のファイルがこちらにはないのですが、大丈夫ですよね？ 🤔
```
bitrise.yml
step.sh
```

**Comment by jmatsu** [comment]
#25 がこの workflow の実行例なので、問題ないです。

**Review by enomoto-kazuya — APPROVED** [review]
LGTMです！

**Comment by jmatsu** [comment]
Thanks~

**Pull request merged**
